[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "2.2.1"
update_changelog_on_bump = true

[tool.commitizen.customizations]
commit_url_format = "https://github.com/parth-parmar-techno/drfCommitizen-ts/commit/{hash}"
